### PR TITLE
WIP: sign debug credential signing requests

### PR DESCRIPTION
**Pull request by mx-shift**

### CODE REVIEW

**Comment by flihp** [comment]
On the whole this looks great. Any thoughts on how you'd like to go about testing w/ staging?

**Comment by mx-shift** [comment]
I've already tested with a sandbox environment and verified it does produce usable debug credentials.  I see having a log of issued debug credentials as a blocker to using this on staging/production.  I'm kinda stuck on what to put in the audit log.  The debug credential doesn't have a field for a serial number or other unique identifier.

**Comment by flihp** [comment]
In lieu of a serial number we could track issued credentials by their hash? AFAIK this is mostly how CAs assign serial numbers these days to mitigate chosen prefix collisions.

**Comment by flihp** [comment]
I've added a tool to package a DCSR as produced by the lpc55-support into a form that OKS can ingest. This is analogous to the CSR spec and so we call it a DCSR spec. This tool is used to create inputs to OKS and the structure overlapped a bit w/ this PR and so I've taken a struct from here and rebased.

**Comment by flihp** [comment]
I've done some basic tire kicking and the signing process seems to work as expected. I still haven't sorted out how to track the debug credentials we've issued and whether or not we need to implement policy preventing things like issuing DCs for the same key etc but this can be done after this is merged.

**Review by flihp — APPROVED** [review]

**Pull request merged**
